// Code generated by scripts/generate.py. DO NOT EDIT.
package robotomail

type ErrorBody struct {
	Error string `json:"error"`
}

type EndpointNotFound struct {
	Error      string                     `json:"error"`
	Code       string                     `json:"code"`
	Message    string                     `json:"message"`
	Resolution EndpointNotFoundResolution `json:"resolution"`
}

type UpgradeHint struct {
	BrowserUrl  string                 `json:"browserUrl"`
	ApiEndpoint UpgradeHintApiEndpoint `json:"apiEndpoint"`
	Hint        string                 `json:"hint"`
}

type PaymentRequired struct {
	Error           string      `json:"error"`
	PaymentRequired bool        `json:"payment_required"`
	Code            string      `json:"code"`
	Upgrade         UpgradeHint `json:"upgrade"`
}

type TrialPaymentRequired struct {
	Error           string      `json:"error"`
	PaymentRequired bool        `json:"payment_required"`
	Code            string      `json:"code"`
	Upgrade         UpgradeHint `json:"upgrade"`
	ResetsAt        *string     `json:"resetsAt,omitempty"`
}

type InboundLimitExceeded struct {
	Error    string                       `json:"error"`
	Code     string                       `json:"code"`
	Resource InboundLimitExceededResource `json:"resource"`
	Upgrade  UpgradeHint                  `json:"upgrade"`
	Recovery string                       `json:"recovery"`
	ResetAt  *string                      `json:"resetAt,omitempty"`
}

type PlanLimit struct {
	Error   string `json:"error"`
	Upgrade string `json:"upgrade"`
}

type Suspended struct {
	Error     string `json:"error"`
	Suspended bool   `json:"suspended"`
	Reason    string `json:"reason"`
}

type DeletedResponse struct {
	Deleted bool `json:"deleted"`
}

type RevokedResponse struct {
	Revoked bool `json:"revoked"`
}

type SignupRequest struct {
	Email          string  `json:"email"`
	Password       string  `json:"password"`
	Slug           string  `json:"slug"`
	Name           *string `json:"name,omitempty"`
	Plan           *string `json:"plan,omitempty"`
	Period         *string `json:"period,omitempty"`
	TurnstileToken *string `json:"turnstileToken,omitempty"`
}

type SignupResponse struct {
	User             SignupResponseUser      `json:"user"`
	ApiKey           SignupResponseApiKey    `json:"api_key"`
	Mailbox          SignupResponseMailbox   `json:"mailbox"`
	MailboxLimit     int64                   `json:"mailbox_limit"`
	DailySendLimit   int64                   `json:"daily_send_limit"`
	MonthlySendLimit int64                   `json:"monthly_send_limit"`
	EmailVerified    bool                    `json:"email_verified"`
	NextSteps        SignupResponseNextSteps `json:"next_steps"`
}

type SandboxTrial struct {
	IsTrialUser       bool     `json:"isTrialUser"`
	Active            bool     `json:"active"`
	Expired           bool     `json:"expired"`
	Exhausted         bool     `json:"exhausted"`
	SendsUsed         int64    `json:"sendsUsed"`
	SendsRemaining    int64    `json:"sendsRemaining"`
	SendCap           int64    `json:"sendCap"`
	ReceivesUsed      int64    `json:"receivesUsed"`
	ReceivesRemaining int64    `json:"receivesRemaining"`
	ReceiveCap        int64    `json:"receiveCap"`
	ExpiresAt         *string  `json:"expiresAt"`
	StartedAt         *string  `json:"startedAt"`
	ResetsAt          **string `json:"resetsAt,omitempty"`
}

type Account struct {
	Id                       string                    `json:"id"`
	Email                    string                    `json:"email"`
	EmailVerified            bool                      `json:"emailVerified"`
	Slug                     string                    `json:"slug"`
	Plan                     string                    `json:"plan"`
	BillingPeriod            string                    `json:"billingPeriod"`
	Suspended                bool                      `json:"suspended"`
	SuspendedReason          *string                   `json:"suspendedReason"`
	SuspendedAt              *string                   `json:"suspendedAt"`
	StorageUsedBytes         int64                     `json:"storageUsedBytes"`
	StorageLimitBytes        int64                     `json:"storageLimitBytes"`
	MailboxCount             int64                     `json:"mailboxCount"`
	ActiveMailboxCount       int64                     `json:"activeMailboxCount"`
	SentToday                int64                     `json:"sentToday"`
	SentThisMonth            int64                     `json:"sentThisMonth"`
	ReceivedToday            int64                     `json:"receivedToday"`
	BouncedToday             int64                     `json:"bouncedToday"`
	MonthlyInboundCount      int64                     `json:"monthlyInboundCount"`
	MonthlyInboundLimit      int64                     `json:"monthlyInboundLimit"`
	MonthlyInboundPercentage int64                     `json:"monthlyInboundPercentage"`
	MonthlyInboundResetAt    string                    `json:"monthlyInboundResetAt"`
	OverLimitMessageCount    int64                     `json:"overLimitMessageCount"`
	BillingLinked            bool                      `json:"billingLinked"`
	AnnualAvailability       AccountAnnualAvailability `json:"annualAvailability"`
	Trial                    *SandboxTrial             `json:"trial"`
}

type AccountResponse struct {
	Account Account `json:"account"`
}

type ApiKeySummary struct {
	Id        string  `json:"id"`
	Name      *string `json:"name"`
	Prefix    *string `json:"prefix"`
	CreatedAt string  `json:"createdAt"`
	Enabled   bool    `json:"enabled"`
}

type ApiKeyListResponse struct {
	Keys []ApiKeySummary `json:"keys"`
}

type CreateApiKeyRequest struct {
	Name       *string   `json:"name,omitempty"`
	MailboxIds *[]string `json:"mailboxIds,omitempty"`
}

type CreateApiKeyResponse struct {
	Key    string `json:"key"`
	Prefix string `json:"prefix"`
	Scoped bool   `json:"scoped"`
}

type Mailbox struct {
	Id                   string  `json:"id"`
	UserId               string  `json:"userId"`
	DomainId             *string `json:"domainId"`
	Address              string  `json:"address"`
	FullAddress          string  `json:"fullAddress"`
	DisplayName          *string `json:"displayName"`
	DailySendCount       int64   `json:"dailySendCount"`
	DailySendLimit       int64   `json:"dailySendLimit"`
	MonthlySendCount     int64   `json:"monthlySendCount"`
	MonthlySendLimit     int64   `json:"monthlySendLimit"`
	Status               string  `json:"status"`
	PausedByBilling      bool    `json:"pausedByBilling"`
	StalwartProvisioned  bool    `json:"stalwartProvisioned"`
	SuspendedAt          *string `json:"suspendedAt"`
	SuspendedReason      *string `json:"suspendedReason"`
	SuspensionIncidentId *string `json:"suspensionIncidentId"`
	CreatedAt            string  `json:"createdAt"`
	UpdatedAt            string  `json:"updatedAt"`
	ReceivedThisMonth    *int64  `json:"receivedThisMonth,omitempty"`
}

type MailboxResponse struct {
	Mailbox Mailbox `json:"mailbox"`
}

type MailboxListResponse struct {
	Mailboxes []Mailbox `json:"mailboxes"`
}

type CreateMailboxRequest struct {
	Address     string  `json:"address"`
	DomainId    *string `json:"domainId,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
}

type UpdateMailboxRequest struct {
	DisplayName *string `json:"displayName,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type SendMessageRequest struct {
	To          []string           `json:"to"`
	Cc          *[]string          `json:"cc,omitempty"`
	Subject     string             `json:"subject"`
	BodyText    string             `json:"bodyText"`
	BodyHtml    *string            `json:"bodyHtml,omitempty"`
	InReplyTo   *string            `json:"inReplyTo,omitempty"`
	Attachments *[]string          `json:"attachments,omitempty"`
	Headers     *map[string]string `json:"headers,omitempty"`
}

type Message struct {
	Id                       string         `json:"id"`
	MailboxId                string         `json:"mailboxId"`
	Direction                string         `json:"direction"`
	MessageId                string         `json:"messageId"`
	InReplyTo                *string        `json:"inReplyTo"`
	ThreadId                 *string        `json:"threadId"`
	FromAddress              string         `json:"fromAddress"`
	ToAddresses              []string       `json:"toAddresses"`
	CcAddresses              []string       `json:"ccAddresses"`
	Subject                  string         `json:"subject"`
	BodyText                 string         `json:"bodyText"`
	BodyHtml                 *string        `json:"bodyHtml"`
	Headers                  map[string]any `json:"headers"`
	Status                   string         `json:"status"`
	ExternalMessageId        *string        `json:"externalMessageId"`
	HasAttachments           bool           `json:"hasAttachments"`
	AttachmentsDropped       bool           `json:"attachmentsDropped"`
	AttachmentsDroppedReason *string        `json:"attachmentsDroppedReason"`
	EventDispatchedAt        *string        `json:"eventDispatchedAt"`
	OverLimit                bool           `json:"overLimit"`
	OverLimitReason          *string        `json:"overLimitReason"`
	PendingSseEventData      any            `json:"pendingSseEventData"`
	CreatedAt                string         `json:"createdAt"`
	Attachments              *[]Attachment  `json:"attachments,omitempty"`
}

type MessageResponse struct {
	Message Message `json:"message"`
}

type InboundUsage struct {
	Current    int64  `json:"current"`
	Limit      int64  `json:"limit"`
	Percentage int64  `json:"percentage"`
	ResetDate  string `json:"reset_date"`
	Status     string `json:"status"`
}

type ListMetadata struct {
	OverLimitCount int64         `json:"overLimitCount"`
	Upgrade        UpgradeHint   `json:"upgrade"`
	LimitHint      *InboundUsage `json:"limitHint,omitempty"`
}

type MessageListResponse struct {
	Messages []Message    `json:"messages"`
	Metadata ListMetadata `json:"metadata"`
}

type Attachment struct {
	Id          string  `json:"id"`
	MessageId   *string `json:"messageId"`
	UserId      string  `json:"userId"`
	Filename    string  `json:"filename"`
	ContentType string  `json:"contentType"`
	SizeBytes   int64   `json:"sizeBytes"`
	R2Key       string  `json:"r2Key"`
	ContentId   *string `json:"contentId"`
	CreatedAt   string  `json:"createdAt"`
}

type AttachmentUploadResponse struct {
	Id        string `json:"id"`
	Filename  string `json:"filename"`
	SizeBytes int64  `json:"sizeBytes"`
}

type AttachmentDownload struct {
	Id          string  `json:"id"`
	MessageId   *string `json:"messageId"`
	UserId      string  `json:"userId"`
	Filename    string  `json:"filename"`
	ContentType string  `json:"contentType"`
	SizeBytes   int64   `json:"sizeBytes"`
	R2Key       string  `json:"r2Key"`
	ContentId   *string `json:"contentId"`
	CreatedAt   string  `json:"createdAt"`
	Url         string  `json:"url"`
}

type Thread struct {
	Id            string   `json:"id"`
	MailboxId     string   `json:"mailboxId"`
	Subject       string   `json:"subject"`
	MessageCount  int64    `json:"messageCount"`
	LastMessageAt string   `json:"lastMessageAt"`
	Participants  []string `json:"participants"`
	CreatedAt     string   `json:"createdAt"`
}

type ThreadDetail struct {
	Id            string    `json:"id"`
	MailboxId     string    `json:"mailboxId"`
	Subject       string    `json:"subject"`
	MessageCount  int64     `json:"messageCount"`
	LastMessageAt string    `json:"lastMessageAt"`
	Participants  []string  `json:"participants"`
	CreatedAt     string    `json:"createdAt"`
	Messages      []Message `json:"messages"`
}

type ThreadListResponse struct {
	Threads  []Thread     `json:"threads"`
	Metadata ListMetadata `json:"metadata"`
}

type ThreadResponse struct {
	Thread ThreadDetail `json:"thread"`
}

type Domain struct {
	Id                  string  `json:"id"`
	UserId              string  `json:"userId"`
	Domain              string  `json:"domain"`
	Status              string  `json:"status"`
	MxVerified          bool    `json:"mxVerified"`
	SpfVerified         bool    `json:"spfVerified"`
	DkimVerified        bool    `json:"dkimVerified"`
	DmarcVerified       bool    `json:"dmarcVerified"`
	DkimPublicKey       *string `json:"dkimPublicKey"`
	DkimSelector        *string `json:"dkimSelector"`
	ExternalDomainId    *string `json:"externalDomainId"`
	StalwartProvisioned bool    `json:"stalwartProvisioned"`
	CreatedAt           string  `json:"createdAt"`
	UpdatedAt           string  `json:"updatedAt"`
}

type MxDnsRecord struct {
	Type     string `json:"type"`
	Host     string `json:"host"`
	Value    string `json:"value"`
	Priority int64  `json:"priority"`
}

type TxtDnsRecord struct {
	Type  string `json:"type"`
	Host  string `json:"host"`
	Value string `json:"value"`
}

type DkimDnsRecord struct {
	Type  string `json:"type"`
	Host  string `json:"host"`
	Value string `json:"value"`
}

type DnsRecords struct {
	Mx     MxDnsRecord     `json:"mx"`
	SendMx MxDnsRecord     `json:"sendMx"`
	Spf    TxtDnsRecord    `json:"spf"`
	Dkim   []DkimDnsRecord `json:"dkim"`
	Dmarc  TxtDnsRecord    `json:"dmarc"`
}

type CreateDomainRequest struct {
	Domain string `json:"domain"`
}

type DomainListResponse struct {
	Domains []Domain `json:"domains"`
}

type DomainCreatedResponse struct {
	Domain     Domain     `json:"domain"`
	DnsRecords DnsRecords `json:"dnsRecords"`
}

type DomainResponse struct {
	Domain     Domain      `json:"domain"`
	DnsRecords *DnsRecords `json:"dnsRecords"`
}

type DomainVerificationResponse struct {
	Domain       Domain                                 `json:"domain"`
	Verification DomainVerificationResponseVerification `json:"verification"`
}

type Webhook struct {
	Id              string             `json:"id"`
	UserId          string             `json:"userId"`
	MailboxId       *string            `json:"mailboxId"`
	Url             string             `json:"url"`
	Events          []string           `json:"events"`
	Headers         *map[string]string `json:"headers"`
	Status          string             `json:"status"`
	FailureCount    int64              `json:"failureCount"`
	LastTriggeredAt *string            `json:"lastTriggeredAt"`
	CreatedAt       string             `json:"createdAt"`
	UpdatedAt       string             `json:"updatedAt"`
}

type WebhookCreated struct {
	Id              string             `json:"id"`
	UserId          string             `json:"userId"`
	MailboxId       *string            `json:"mailboxId"`
	Url             string             `json:"url"`
	Events          []string           `json:"events"`
	Headers         *map[string]string `json:"headers"`
	Status          string             `json:"status"`
	FailureCount    int64              `json:"failureCount"`
	LastTriggeredAt *string            `json:"lastTriggeredAt"`
	CreatedAt       string             `json:"createdAt"`
	UpdatedAt       string             `json:"updatedAt"`
	Secret          string             `json:"secret"`
}

type WebhookHeaders map[string]string
type CreateWebhookRequest struct {
	Url       string          `json:"url"`
	MailboxId *string         `json:"mailboxId,omitempty"`
	Events    []string        `json:"events"`
	Headers   *WebhookHeaders `json:"headers,omitempty"`
}

type UpdateWebhookRequest struct {
	Url     *string          `json:"url,omitempty"`
	Events  *[]string        `json:"events,omitempty"`
	Status  *string          `json:"status,omitempty"`
	Headers **WebhookHeaders `json:"headers,omitempty"`
}

type WebhookListResponse struct {
	Webhooks []Webhook `json:"webhooks"`
}

type WebhookResponse struct {
	Webhook Webhook `json:"webhook"`
}

type WebhookCreatedResponse struct {
	Webhook WebhookCreated `json:"webhook"`
}

type WebhookDelivery struct {
	Id             string  `json:"id"`
	Event          string  `json:"event"`
	ResponseStatus *int64  `json:"responseStatus"`
	Status         string  `json:"status"`
	Attempts       int64   `json:"attempts"`
	NextRetryAt    *string `json:"nextRetryAt"`
	CreatedAt      string  `json:"createdAt"`
}

type WebhookDeliveryListResponse struct {
	Deliveries []WebhookDelivery `json:"deliveries"`
}

type SuppressionEntry struct {
	Id        string `json:"id"`
	Email     string `json:"email"`
	Reason    string `json:"reason"`
	CreatedAt string `json:"createdAt"`
}

type CreateSuppressionRequest struct {
	Email  string  `json:"email"`
	Reason *string `json:"reason,omitempty"`
}

type SuppressionListResponse struct {
	Suppressions []SuppressionEntry `json:"suppressions"`
}

type SuppressionResponse struct {
	Suppression SuppressionEntry `json:"suppression"`
}

type UpgradeRequest struct {
	Plan   *string `json:"plan,omitempty"`
	Period *string `json:"period,omitempty"`
}

type UpgradeCheckoutResponse struct {
	CheckoutUrl string `json:"checkout_url"`
	ExpiresAt   *int64 `json:"expires_at"`
	Message     string `json:"message"`
}

type SupportRequest struct {
	Category string `json:"category"`
	Subject  string `json:"subject"`
	Message  string `json:"message"`
}

type OkResponse struct {
	Ok bool `json:"ok"`
}

type SlugAvailability struct {
	Available bool    `json:"available"`
	Reason    *string `json:"reason,omitempty"`
}

type CheckSlugAvailabilityParams struct {
	Slug string `json:"slug"`
}

type DeleteAccountRequest struct {
	Confirm string `json:"confirm"`
}

type SetPostVerifyTargetResponse struct {
	Target string `json:"target"`
}

type ListMessagesParams struct {
	Direction *string `json:"direction,omitempty"`
	ThreadId  *string `json:"threadId,omitempty"`
	Since     *string `json:"since,omitempty"`
	Limit     *int64  `json:"limit,omitempty"`
	Offset    *int64  `json:"offset,omitempty"`
}

type StreamEventsParams struct {
	MailboxId   *string `json:"mailboxId,omitempty"`
	Events      *string `json:"events,omitempty"`
	LastEventID *string `json:"Last-Event-ID,omitempty"`
}

type ResendVerificationEmailRequest struct {
	Email string `json:"email"`
}

type EndpointNotFoundResolution struct {
	Openapi         string   `json:"openapi"`
	Docs            string   `json:"docs"`
	Endpoints       string   `json:"endpoints"`
	CommonEndpoints []string `json:"commonEndpoints"`
}

type UpgradeHintApiEndpoint struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

type InboundLimitExceededResource struct {
	Type string `json:"type"`
	Id   string `json:"id"`
}

type SignupResponseUser struct {
	Id            string `json:"id"`
	Email         string `json:"email"`
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	Plan          string `json:"plan"`
	PlatformEmail string `json:"platform_email"`
}

type SignupResponseApiKey struct {
	Key    string `json:"key"`
	Prefix string `json:"prefix"`
	Name   string `json:"name"`
}

type SignupResponseMailbox struct {
	Id          string `json:"id"`
	Address     string `json:"address"`
	FullAddress string `json:"fullAddress"`
	Status      string `json:"status"`
}

type SignupResponseNextSteps struct {
	VerifyEmail string `json:"verify_email"`
	AddPayment  string `json:"add_payment"`
	AddDomain   string `json:"add_domain"`
	SendEmail   string `json:"send_email"`
}

type AccountAnnualAvailability struct {
	Developer bool `json:"developer"`
	Growth    bool `json:"growth"`
	Scale     bool `json:"scale"`
}

type DomainVerificationResponseVerification struct {
	Mx          bool `json:"mx"`
	Spf         bool `json:"spf"`
	Dkim        bool `json:"dkim"`
	Dmarc       bool `json:"dmarc"`
	AllVerified bool `json:"allVerified"`
}
