// Code generated by scripts/generate.py. DO NOT EDIT.
package robotomail

import (
	"context"
	"net/url"
)

// CreateSignup Create an account.
func (c *Client) CreateSignup(ctx context.Context, body SignupRequest) (*SignupResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result SignupResponse
	err := c.request(ctx, "POST", "/signup", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CheckSlugAvailability Check if an account slug is available.
func (c *Client) CheckSlugAvailability(ctx context.Context, params *CheckSlugAvailabilityParams) (*SlugAvailability, error) {
	query := url.Values{}
	headers := map[string]string{}
	if params != nil {
		query.Set("slug", queryValue(params.Slug))
	}
	var result SlugAvailability
	err := c.request(ctx, "GET", "/signup/check-slug", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetAccount Get account stats.
func (c *Client) GetAccount(ctx context.Context) (*AccountResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result AccountResponse
	err := c.request(ctx, "GET", "/account", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteAccount Delete account permanently.
func (c *Client) DeleteAccount(ctx context.Context, body DeleteAccountRequest) (*DeletedResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result DeletedResponse
	err := c.request(ctx, "DELETE", "/account", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SendWelcomeEmail Send the welcome email.
func (c *Client) SendWelcomeEmail(ctx context.Context) (*OkResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result OkResponse
	err := c.request(ctx, "POST", "/account/welcome", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SetPostVerifyTarget Resolve post-verification target.
func (c *Client) SetPostVerifyTarget(ctx context.Context) (*SetPostVerifyTargetResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result SetPostVerifyTargetResponse
	err := c.request(ctx, "POST", "/account/post-verify-target", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListApiKeys List API keys.
func (c *Client) ListApiKeys(ctx context.Context) (*ApiKeyListResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result ApiKeyListResponse
	err := c.request(ctx, "GET", "/api-keys", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateApiKey Create an API key.
func (c *Client) CreateApiKey(ctx context.Context, body CreateApiKeyRequest) (*CreateApiKeyResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result CreateApiKeyResponse
	err := c.request(ctx, "POST", "/api-keys", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// RevokeApiKey Revoke an API key.
func (c *Client) RevokeApiKey(ctx context.Context, id string) (*RevokedResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result RevokedResponse
	err := c.request(ctx, "DELETE", "/api-keys/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListMailboxes List mailboxes.
func (c *Client) ListMailboxes(ctx context.Context) (*MailboxListResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result MailboxListResponse
	err := c.request(ctx, "GET", "/mailboxes", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateMailbox Create a mailbox.
func (c *Client) CreateMailbox(ctx context.Context, body CreateMailboxRequest) (*MailboxResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result MailboxResponse
	err := c.request(ctx, "POST", "/mailboxes", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetMailbox Get a mailbox.
func (c *Client) GetMailbox(ctx context.Context, id string) (*MailboxResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result MailboxResponse
	err := c.request(ctx, "GET", "/mailboxes/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateMailbox Update a mailbox.
func (c *Client) UpdateMailbox(ctx context.Context, id string, body UpdateMailboxRequest) (*MailboxResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result MailboxResponse
	err := c.request(ctx, "PATCH", "/mailboxes/"+escapeSegment(id)+"", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteMailbox Delete a mailbox.
func (c *Client) DeleteMailbox(ctx context.Context, id string) (*DeletedResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result DeletedResponse
	err := c.request(ctx, "DELETE", "/mailboxes/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListMessages List messages in a mailbox.
func (c *Client) ListMessages(ctx context.Context, id string, params *ListMessagesParams) (*MessageListResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	if params != nil {
		if params.Direction != nil {
			query.Set("direction", queryValue(*params.Direction))
		}
		if params.ThreadId != nil {
			query.Set("threadId", queryValue(*params.ThreadId))
		}
		if params.Since != nil {
			query.Set("since", queryValue(*params.Since))
		}
		if params.Limit != nil {
			query.Set("limit", queryValue(*params.Limit))
		}
		if params.Offset != nil {
			query.Set("offset", queryValue(*params.Offset))
		}
	}
	var result MessageListResponse
	err := c.request(ctx, "GET", "/mailboxes/"+escapeSegment(id)+"/messages", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SendMessage Send an email from a mailbox.
func (c *Client) SendMessage(ctx context.Context, id string, body SendMessageRequest) (*MessageResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result MessageResponse
	err := c.request(ctx, "POST", "/mailboxes/"+escapeSegment(id)+"/messages", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetMessage Get a message.
func (c *Client) GetMessage(ctx context.Context, id string, msgId string) (*MessageResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	if err := validateSegment(msgId); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result MessageResponse
	err := c.request(ctx, "GET", "/mailboxes/"+escapeSegment(id)+"/messages/"+escapeSegment(msgId)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListThreads List threads in a mailbox.
func (c *Client) ListThreads(ctx context.Context, id string) (*ThreadListResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result ThreadListResponse
	err := c.request(ctx, "GET", "/mailboxes/"+escapeSegment(id)+"/threads", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetThread Get a thread with its messages.
func (c *Client) GetThread(ctx context.Context, id string, tid string) (*ThreadResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	if err := validateSegment(tid); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result ThreadResponse
	err := c.request(ctx, "GET", "/mailboxes/"+escapeSegment(id)+"/threads/"+escapeSegment(tid)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UploadAttachment Upload an attachment.
func (c *Client) UploadAttachment(ctx context.Context, file Upload) (*AttachmentUploadResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result AttachmentUploadResponse
	err := c.request(ctx, "POST", "/attachments", query, headers, nil, &file, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DownloadAttachment Get an attachment download URL.
func (c *Client) DownloadAttachment(ctx context.Context, id string) (*AttachmentDownload, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result AttachmentDownload
	err := c.request(ctx, "GET", "/attachments/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteAttachment Delete an attachment.
func (c *Client) DeleteAttachment(ctx context.Context, id string) (*DeletedResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result DeletedResponse
	err := c.request(ctx, "DELETE", "/attachments/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListDomains List custom domains.
func (c *Client) ListDomains(ctx context.Context) (*DomainListResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result DomainListResponse
	err := c.request(ctx, "GET", "/domains", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateDomain Add a custom domain.
func (c *Client) CreateDomain(ctx context.Context, body CreateDomainRequest) (*DomainCreatedResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result DomainCreatedResponse
	err := c.request(ctx, "POST", "/domains", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetDomain Get a domain and its DNS records.
func (c *Client) GetDomain(ctx context.Context, id string) (*DomainResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result DomainResponse
	err := c.request(ctx, "GET", "/domains/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteDomain Delete a domain.
func (c *Client) DeleteDomain(ctx context.Context, id string) (*DeletedResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result DeletedResponse
	err := c.request(ctx, "DELETE", "/domains/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// VerifyDomain Trigger domain verification.
func (c *Client) VerifyDomain(ctx context.Context, id string) (*DomainVerificationResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result DomainVerificationResponse
	err := c.request(ctx, "POST", "/domains/"+escapeSegment(id)+"/verify", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListWebhooks List webhooks.
func (c *Client) ListWebhooks(ctx context.Context) (*WebhookListResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result WebhookListResponse
	err := c.request(ctx, "GET", "/webhooks", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateWebhook Create a webhook.
func (c *Client) CreateWebhook(ctx context.Context, body CreateWebhookRequest) (*WebhookCreatedResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result WebhookCreatedResponse
	err := c.request(ctx, "POST", "/webhooks", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// GetWebhook Get a webhook.
func (c *Client) GetWebhook(ctx context.Context, id string) (*WebhookResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result WebhookResponse
	err := c.request(ctx, "GET", "/webhooks/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateWebhook Update a webhook.
func (c *Client) UpdateWebhook(ctx context.Context, id string, body UpdateWebhookRequest) (*WebhookResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result WebhookResponse
	err := c.request(ctx, "PATCH", "/webhooks/"+escapeSegment(id)+"", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteWebhook Delete a webhook.
func (c *Client) DeleteWebhook(ctx context.Context, id string) (*DeletedResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result DeletedResponse
	err := c.request(ctx, "DELETE", "/webhooks/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ListWebhookDeliveries List webhook deliveries.
func (c *Client) ListWebhookDeliveries(ctx context.Context, id string) (*WebhookDeliveryListResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result WebhookDeliveryListResponse
	err := c.request(ctx, "GET", "/webhooks/"+escapeSegment(id)+"/deliveries", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// StreamEvents Stream inbox events over SSE.
func (c *Client) StreamEvents(ctx context.Context, params *StreamEventsParams) (*EventStream, error) {
	query := url.Values{}
	headers := map[string]string{}
	if params != nil {
		if params.MailboxId != nil {
			query.Set("mailboxId", queryValue(*params.MailboxId))
		}
		if params.Events != nil {
			query.Set("events", queryValue(*params.Events))
		}
		if params.LastEventID != nil {
			headers["Last-Event-ID"] = *params.LastEventID
		}
	}
	return c.openStream(ctx, query, headers)
}

// ListSuppressions List suppressed addresses.
func (c *Client) ListSuppressions(ctx context.Context) (*SuppressionListResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result SuppressionListResponse
	err := c.request(ctx, "GET", "/suppressions", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateSuppression Suppress an address.
func (c *Client) CreateSuppression(ctx context.Context, body CreateSuppressionRequest) (*SuppressionResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result SuppressionResponse
	err := c.request(ctx, "POST", "/suppressions", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteSuppression Remove a suppression entry.
func (c *Client) DeleteSuppression(ctx context.Context, id string) (*DeletedResponse, error) {
	if err := validateSegment(id); err != nil {
		return nil, err
	}
	query := url.Values{}
	headers := map[string]string{}
	var result DeletedResponse
	err := c.request(ctx, "DELETE", "/suppressions/"+escapeSegment(id)+"", query, headers, nil, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateUpgradeCheckout Start a plan upgrade.
func (c *Client) CreateUpgradeCheckout(ctx context.Context, body UpgradeRequest) (*UpgradeCheckoutResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result UpgradeCheckoutResponse
	err := c.request(ctx, "POST", "/billing/upgrade", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// ResendVerificationEmail Resend the email verification link.
func (c *Client) ResendVerificationEmail(ctx context.Context, body ResendVerificationEmailRequest) (*OkResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result OkResponse
	err := c.request(ctx, "POST", "/auth/resend-verification", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// SubmitSupportTicket Contact support.
func (c *Client) SubmitSupportTicket(ctx context.Context, body SupportRequest) (*OkResponse, error) {
	query := url.Values{}
	headers := map[string]string{}
	var result OkResponse
	err := c.request(ctx, "POST", "/support", query, headers, body, nil, &result)
	if err != nil {
		return nil, err
	}
	return &result, nil
}
